### ISSUE TITLE
Syntax: functions

### ISSUE THREAD

**Issue by jhayley** [jhayley/bondage.js#15]

**Comment by DigitalMachinist** [comment]
So I put some time into understanding YarnSpinner's lexer and porting it, only to discover a little kink and I wanted to get your thoughts.

First of all, how attached are you to JISON and having the valid syntax described by BNF?

I am finding that YarnSpinner'so lexer/parser is a custom design, and if I try to port it directly (with the intent that bondage's yarn semantics be the same as YarnSpinner) then JISON might as well be dropped from the npm dependencies. This is one path I could go.

The other is to requires that I spend some time integrating the behaviour of my new lexer with JISON's counters and such, then of course working out BNF syntax for Yarn. This will describe the syntax more legibly and probably be better to maintain, but its harder to implement in the short-term and my bet is that we'll end up with small behavioural differences from YarnSpinner.

I lean toward the former, personally, but it's your project so I wanted to know where you intend to go with it before I want ahead and made a big change.

Let me know what you think.

**Comment by jessicahayley** [comment]
I'm leaning towards the latter, though I could be swayed. I'm pretty attached to JISON mostly for the legibility and extensibility, and I'm not opposed to making well-defined/documented tweaks to the existing yarnspinner syntax/functionality.

Is there particular syntax that you're having trouble describing with bnf? Or is this more of a core problem with how I use the lexer vs how yarnspinner does?

**Comment by DigitalMachinist** [comment]
I don't think it's anything insurmountable. Just trying to figure out if I can be intellectually lazy and avoid doing the right thing. lol

The notable difference between YarnSpinner's lexer/parser and JISON is that YarnSpinner's core lexer function returns a collection of all tokens while JISON returns one at a time from lex(). Originally i wasn't sure how to cope with that but I figure I can turn the ported YarnSpinner-style core lexer function into a generator and call it once for each call to lex(). AFAIK that should behave the same as JISON is expecting.

To tell you the truth I've only ever studied BNFs and I've never written one, but I'll give it a try. I haven't yet taken any time to figure out the syntax since I wanted to wait for your input before forging ahead at all.

Thanks for the insight. I'll start into sorting out the lex function and getting the basics into the BNF for now.

**Comment by jessicahayley** [comment]
Yeah, I think doing a more-or-less direct port of the lexer while using jison to handle the parsing should work and give us the best of both worlds.
Let me know if you hit any trouble or need some help with bnf syntax!

**Comment by DigitalMachinist** [comment]
Can do! Thanks for the advice!

**Comment by jhayley** [comment]
This issue is now covered by #17
