### ISSUE TITLE
<<myfunction(stuff)>> - cause parser.js to crash the application

### ISSUE THREAD

**Issue by blurymind** [jhayley/bondage.js#35]
Ok This seems to be a problem with the parser.js

Whenever you have escaped quotation marks inside `<<mytest(\"test\")>>`, this crashes the parser and the object fails to load.

This is the error message
VM122:156 Uncaught Error: Parse error on line 2: Unexpected 'LeftParen'

this is where it happens
`const parserNodes = Array.from(parser.parse(yarnNode.body));`

**Comment by blurymind** [comment]
Ok I have never actually written a parser, so adding a new rule in parser.js is totally over my head. I have no idea how that thing is set up and tutorials seem to be scarce

**Comment by blurymind** [comment]
Adding this line to parser.js > command: [...]
`['BeginCommand Text LeftParen Text RightParen EndCommand', '$$ = new yy.TextNode($2,$3,$4,$5);'],`

This is guessingg the syntax a little bit. I must be getting it wrong

I now get
`VM122:159 Uncaught Error: Parse error on line 11: Unexpected 'EndOfInput'`

**Comment by blurymind** [comment]
ok here goes something, adding:
`['BeginCommand Identifier LeftParen RightParen EndCommand', '$$ = new yy.CommandNode($2,$3,$4,$5);'],`

Now allows me to use <<myfunction()>> 

However, I still need to figure out how to allow triggering a function with parameters

**Comment by blurymind** [comment]
Ok Here when I try the same with parameters:
`['BeginCommand Identifier LeftParen arguments RightParen EndCommand', '$$ = new yy.CommandNode($2+ "("+ $4 + ")");'],  `
The problem is that it is returning myfunction([object object]) instead of myfunction(parameter,parameter)

**Comment by blurymind** [comment]
Ah  ok, sorry for the monologue.. I think I figured it out now and even implemented a new node type (jsEval Node). I added it to my pull request here:
https://github.com/jhayley/bondage.js/pull/33

**Comment by jhayley** [comment]
It looks like this issue is centered around [this](https://github.com/jhayley/bondage.js/blob/master/src/lexer/states.js#L28) line in the lexer states. When this state is arrived at from the `command` state there's no differentiation of whether or not it's coming from at the beginning of a command vs after an `<<if`
This is incorrect because `<<if visited("blah")>> is valid syntax but `<<visited("blah")>>` is not. The latter should be sent to the command handler. (I'm actually not sure how/if this edge case is handled in yarnspinner but I don't have time to test right now).

If you would like to put in a pull request for this, you should be able to fix it by adjusting the lexer states in that file such that it knows that a yarn function cannot be called from the beginning of the command block. Let me know if you have any questions.

Good catch!

**Comment by blurymind** [comment]
@jhayley thank you for helping me understand how this is set up.

We have to remember that yarnspinner was written for Unity specifically and in our case - with bondage.js we really are targetting js based environments, where the `<<functionCall("parameter")>>` syntax would be very useful to allow :)
It doesnt have to negate in any way what is already established

I will look into adding it to the command in another pull request.
Sorry that in the previous pull where I did that by creating a new type

**Comment by blurymind** [comment]
@jhayley the problem with the command handler is that you have to set it in advance:
```
runner.setCommandHandler((command) => {
  // Called whenever there is a <<command>>, the parameter being the text inside
});
```
Where as in my case I want to do it more reactively by using a syntax akin to how text is parsed.
```
  if (result instanceof bondage.CommandResult) {
    console.log(result.text);
}
```
I guess thats why in my previous pull request I created a new node type- so I can return it like that.
Would you be ok If the commandResult gets added as a return type?

**Comment by jhayley** [comment]
> Would you be ok If the commandResult gets added as a return type?

Fun fact, this used to actually be how commands worked. I'm uh...honestly not sure why I changed it. I still only want to have one way to handle commands so we should remove the callback way which means this would be a breaking api change. I think this is an ok change for consistency between callback results, and it makes sense that it would be easier to handle that way. So feel free to change this, it shouldn't be too hard. Also remember to change the readme to reflect this change in the example.
For the record, this part should be a separate pull request.

> Should it be a commandResult type or it's own type (specific to if its detected as a js function call ) like my previous pull?

It should be a CommandResult in results.js

> The advantage of having it be it's own is that you can apply different treatment to
`<<command command>>`and `<<callfunction()>>`

I disagree that these should be handled as separate cases. We should leave it up to the user to discern the difference between them. Handling it in bondage is undeeded complexity and obfuscates things for people that expect to be able to use parenthesis in commands and have them returned as strings which is the expected behaviour generally for commands.

**Comment by blurymind** [comment]
closed via https://github.com/jhayley/bondage.js/pull/40

Thank you @jhayley for reviewing this and for explaining some of the workings of the lexer :) 👍
